name: E2E Tests

on:
  push:
    branches: [main, master, feat/**]
  pull_request:

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (clean)
        run: npm ci

      - name: Install Playwright (Chromium only + system deps)
        run: npx playwright install --with-deps chromium

      - name: Run tests (headed via XVFB)
        env:
          DEBUG: pw:api
        run: xvfb-run --auto-servernum -- npm test

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload test results and traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7
          if-no-files-found: ignore
